'use client';
import { Github } from '@/components/brand-icons';
import { useState } from 'react';
import { portfolio } from '@/data/portfolio';
import { SectionHeading, ExternalLink } from '@/components/shared';
import { BriefcaseBusiness, ArrowUpRight, Check, Circle, BookOpen, GraduationCap, GitBranch } from 'lucide-react';
export function Experience(){return <section id="experience" className="section shell"><div className="experience-layout"><SectionHeading number="06" label="EXPERIENCE" title={'Learning through\nreal work.'} description="Internship assignments and practical exercises that strengthened my technical foundations and documentation habits."/><div className="experience-timeline">{portfolio.experience.map(e=><article className="experience-item" key={e.organization}><span className="timeline-marker"><BriefcaseBusiness size={15}/></span><div className="experience-meta"><span className="eyebrow">{e.duration}</span><span>{e.dates??'Dates not listed'}</span></div><h3>{e.role}</h3><h4>{e.organization}</h4><ul>{e.responsibilities.map(r=><li key={r}>{r}</li>)}</ul><div className="tags">{e.technologies.map(t=><span key={t}>{t}</span>)}</div>{e.projects.map(link=><ExternalLink key={link} href={link}>View internship work<ArrowUpRight size={15}/></ExternalLink>)}{e.certificate&&<ExternalLink href={e.certificate}>Certificate<ArrowUpRight size={15}/></ExternalLink>}{e.verificationUrl&&<ExternalLink href={e.verificationUrl}>Verify experience<ArrowUpRight size={15}/></ExternalLink>}</article>)}</div></div></section>}
export function Journey(){const[selected,setSelected]=useState(4);return <section id="journey" className="section shell journey-section"><SectionHeading number="07" label="THE LEARNING JOURNEY" title="Always in development." description="Foundations practiced, skills being sharpened, and the direction I’m working toward."/><div className="journey-legend"><span><Check size={13}/>Practiced</span><span><span className="current-dot"/>Current focus</span><span><Circle size={11}/>Developing / up next</span></div><div className="journey-track">{portfolio.learning.map((s,i)=><button key={s.name} className={`journey-stage ${s.status==='Practiced'?'completed':s.status==='Current focus'?'current':'pending'} ${selected===i?'selected':''}`} onClick={()=>setSelected(i)} aria-pressed={selected===i} aria-controls="journey-detail"><span className="journey-dot">{s.status==='Practiced'?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><strong>{s.name}</strong><small>{s.status}</small></button>)}</div><div className="journey-detail" id="journey-detail" aria-live="polite"><BookOpen size={19}/><strong>{portfolio.learning[selected].name}</strong><p>{portfolio.learning[selected].detail}</p></div><div className="training-header"><h3>Certifications & training</h3><span>Completed job simulations · listed in my resume</span></div><div className="certifications">{portfolio.certifications.map(c=><article className="certificate" key={c.organization}><div className="certificate-icon"><GraduationCap size={24}/></div><div><span className="tiny-label">{c.organization}</span><h4>{c.name}</h4><span className="certificate-date">{c.date}</span><div className="tags">{c.skills.map(s=><span key={s}>{s}</span>)}</div>{c.credentialUrl?<ExternalLink href={c.credentialUrl}>View credential<ArrowUpRight size={15}/></ExternalLink>:<span className="credential-pending">Credential link not supplied</span>}</div></article>)}</div><p className="training-note">Job simulations are learning experiences; they are not employment at the named organizations or professional certification exams.</p></section>}
export function TechnicalWork(){return <section className="section technical-section" id="github"><div className="shell"><div className="heading-row"><SectionHeading number="08" label="OPEN TECHNICAL WORK" title="The work is in the details." description="Explore source code, lab notes and documented findings in my public repositories."/><ExternalLink href={portfolio.socials.github} className="button"><Github size={17}/>GitHub profile<ArrowUpRight size={16}/></ExternalLink></div><div className="repo-list">{portfolio.repositories.map(r=><ExternalLink key={r.name} href={r.url} className="repo-row"><GitBranch size={21}/><div><h3>{r.name}</h3><p>{r.description}</p></div><span className="repo-language">{r.language}</span><ArrowUpRight size={19}/></ExternalLink>)}</div><p className="repo-note">Selected public repositories · no simulated contribution counts. For current activity, visit GitHub.</p></div></section>}
