'use client';
import { Github, Linkedin } from '@/components/brand-icons';
import { useEffect,useState } from 'react';
import { Menu, ArrowUpRight } from 'lucide-react';
import { Dialog, DialogContent, DialogTrigger, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { portfolio } from '@/data/portfolio';
import { ExternalLink } from './shared';
const links=['Home','Projects','About','Skills','Experience','Resume','Contact'];
export default function Navigation(){const[compact,setCompact]=useState(false);const[open,setOpen]=useState(false);const[active,setActive]=useState('home');useEffect(()=>{const scroll=()=>setCompact(window.scrollY>25);window.addEventListener('scroll',scroll,{passive:true});scroll();const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)})},{rootMargin:'-15% 0px -60% 0px'});links.forEach(l=>{const e=document.getElementById(l.toLowerCase());if(e)observer.observe(e)});return()=>{window.removeEventListener('scroll',scroll);observer.disconnect()}},[]);return <><a className="skip-link" href="#main">Skip to content</a><header className={`nav-wrap ${compact?'compact':''}`}><nav aria-label="Main navigation" className="nav shell"><a className="brand" href="#home" aria-label={`${portfolio.personal.name}, home`}><span className="monogram">S<span>.</span></span><span>{portfolio.personal.name}<span className="brand-sub">Security operations</span></span></a><div className="nav-links">{links.map(link=><a aria-current={active===link.toLowerCase()?'location':undefined} key={link} href={`#${link.toLowerCase()}`}>{link}</a>)}</div><div className="nav-actions"><ExternalLink href={portfolio.socials.github} className="icon-link desktop-social" label={`${portfolio.personal.name} on GitHub`}><Github size={18}/></ExternalLink><ExternalLink href={portfolio.socials.linkedin} className="icon-link desktop-social" label={`${portfolio.personal.name} on LinkedIn`}><Linkedin size={18}/></ExternalLink><a className="button small nav-resume" href={portfolio.resume.path} target="_blank" rel="noopener noreferrer">Resume <ArrowUpRight size={15}/></a><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button className="menu-button icon-link" aria-label="Open navigation"><Menu size={22}/></button></DialogTrigger><DialogContent className="mobile-menu"><DialogTitle>Explore the portfolio</DialogTitle><DialogDescription>{portfolio.personal.name} · Security operations</DialogDescription><div className="mobile-links">{links.map(link=><a key={link} href={`#${link.toLowerCase()}`} onClick={()=>setOpen(false)}>{link}<ArrowUpRight size={18}/></a>)}</div><div className="actions"><ExternalLink href={portfolio.socials.github}><Github size={18}/>GitHub</ExternalLink><ExternalLink href={portfolio.socials.linkedin}><Linkedin size={18}/>LinkedIn</ExternalLink></div></DialogContent></Dialog></div></nav></header></>}
