import { ArrowUpRight, Network, Database, Monitor, ShieldCheck, FileText, Search, Layers, Plus } from 'lucide-react';
import type { Project } from '@/types/portfolio';
import type { ReactNode } from 'react';
export function ExternalLink({href,children,className='text-link',label}:{href:string;children:ReactNode;className?:string;label?:string}){return <a href={href} target="_blank" rel="noopener noreferrer" className={className} aria-label={label}>{children}</a>}
export function SectionHeading({number,label,title,description}:{number:string;label:string;title:string;description?:string}){return <div className="section-heading"><div className="eyebrow"><span className="section-number">{number}</span>{label}</div><h2>{title}</h2>{description&&<p>{description}</p>}</div>}
export function ProjectVisual({project,large=false,showThumbnail=true}:{project:Project;large?:boolean;showThumbnail?:boolean}){
 if(project.thumbnail&&showThumbnail)return <div className="project-screenshot"><span className="visual-meta">RECORDED PROJECT INTERFACE</span><img src={project.thumbnail} alt={`${project.name}: operations overview from the September 2026 project recording; synthetic training data`} width="1902" height="978" loading="lazy" decoding="async" className="project-photo"/><span className="screenshot-caption">Actual project capture <span>· Synthetic training data</span></span></div>;
 const groups={sentinel:[{icon:Layers,name:'Alert queue',hint:'Detect'},{icon:Search,name:'Evidence',hint:'Investigate'},{icon:FileText,name:'Case record',hint:'Document'}],dashboard:[{icon:ShieldCheck,name:'SIEM alert',hint:'Triage'},{icon:Monitor,name:'Endpoint',hint:'Correlate'},{icon:FileText,name:'Analyst notes',hint:'Decide'}],lab:[{icon:Monitor,name:'Kali Linux',hint:'Workstation'},{icon:Network,name:'Isolated network',hint:'Host-only'},{icon:Database,name:'Lab endpoints',hint:'Windows / target'}],next:[{icon:Plus,name:'Next project',hint:'Scope to be defined'}]};
 return <div className={`project-visual ${project.kind} ${large?'large':''}`} role="img" aria-label={`${project.name}: conceptual architecture diagram, not a screenshot`}><span className="visual-meta">{project.kind==='next'?'RESEARCH / NEXT':'PROJECT ARCHITECTURE'}</span><div className="visual-flow">{groups[project.kind].map((n,i)=><div className="visual-node" key={n.name}><span className="node-icon"><n.icon size={large?23:20}/></span><strong>{n.name}</strong><small>{n.hint}</small>{i<groups[project.kind].length-1&&<span className="connector" aria-hidden="true"/>}</div>)}</div><span className="visual-caption">{project.kind==='lab'?'Controlled environment · personal lab':project.kind==='next'?'A placeholder for the work ahead':'Synthetic data · investigation practice'}</span></div>
}
export function SourceLink({href,label}:{href:string;label:string}){return <ExternalLink href={href}>{label}<ArrowUpRight size={15}/></ExternalLink>}
